development:
  adapter: mysql2
  encoding: utf8
  database: edik_dev
  username: root
  password: root
  host: localhost
  
test:
  adapter: mysql2
  encoding: utf8
  database: edik_test
  username: root
  password: root
  host: localhost  